### ISSUE TITLE
Doesn't compile with GHC 9.4.2 due to the upper bound on hashable

### ISSUE THREAD

**Issue by Mikolaj** [haskellari/strict-containers#7]
Adding `--allow-newer=strict-containers:hashable` makes it compile. Without it, I'm getting

```
[__1] trying: strict-containers-0.1 (dependency of horde-ad)
[__2] next goal: hashable (dependency of strict-containers)
[__2] rejecting: hashable-1.4.1.0 (conflict: strict-containers =>
hashable>=1.2.7.0 && <1.4)
[__2] skipping: hashable-1.4.0.2, hashable-1.4.0.1, hashable-1.4.0.0 (has the
same characteristics that caused the previous version to fail: excluded by
constraint '>=1.2.7.0 && <1.4' from 'strict-containers')
[__2] trying: hashable-1.3.5.0
[__3] next goal: base (dependency of horde-ad)
[__3] rejecting: base-4.17.0.0/installed-4.17.0.0 (conflict: hashable =>
base>=4.5 && <4.17)
```

**Comment by Mikolaj** [comment]
Actually, I was wrong, it doesn't compile, but I don't understand the error:

```
src/Data/Strict/Vector/Internal.hs:49:11: error:
    Variable not in scope: genericPutVector :: S.Vector a -> Put
   |
49 |     put = genericPutVector
   |           ^^^^^^^^^^^^^^^^

src/Data/Strict/Vector/Internal.hs:50:11: error:
    Variable not in scope: genericGetVector :: Get (S.Vector a)
   |
50 |     get = genericGetVector
   |           ^^^^^^^^^^^^^^^^
Error: cabal: Failed to build strict-containers-0.1 (which is required by
bench:realisticMnistBench from horde-ad-0.1.0.0). See the build log above for
details.
```

**Comment by Mikolaj** [comment]
However, with `--constraint "vector < 0.13" --allow-newer` it compiles fine.

**Comment by Mikolaj** [comment]
A friendly ping?

**Comment by Mikolaj** [comment]
@infinity0: thank you!
